baseURL: "http://ott-experts.github.io/"
languageCode: "en-us"
title: "OTT-EXPERTS"
theme: "ananke"
taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
permalinks:
  posts: /:year/:month/:slug/
DefaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    languageName: English
    weight: 1
  pl:
    languageName: Polski
    weight: 2
